services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /opt/stacks/adguardhome/config:/opt/adguardhome/conf
      - /opt/stacks/adguardhome/data:/opt/adguardhome/data
    ports:
      - 3000:3000 #port WebUI
      - 53:53/tcp
      - 53:53/udp
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 10.0.0.20
networks:
  macvlan:
    external: true
