services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./sonarr/data:/config
      - ./jellyfin/data/tvshows:/tvshows
      - ./qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      #- UMASK_SET=022 # control permissions of files and directories created by Radarr
      - TZ=Asia/Jakarta
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jellyfin/data/movies:/movies
      - ./qbittorrent/downloads:/downloads
      - ./radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./lidarr/config:/config
      - ./jellyfin/data/music:/music #optional
      - ./qbittorrent/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - WEBUI_PORT=10010
    dns:
      - 1.1.1.1
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
      - ./jellyfin/data/tvshows:/tvshows
      - ./jellyfin/data/movies:/movies
    ports:
      - 10010:10010
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta

    volumes:
      - ./jellyfin/data/library:/config
      - ./jellyfin/data/tvshows:/data/tvshows
      - ./jellyfin/data/movies:/data/movies
      - ./jellyfin/data/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped

  byparr: # For bypass cloudflare challenge
    image: ghcr.io/thephaseless/byparr
    container_name: byparr
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./screenshots:/app/screenshots # For screenshots when exception occurs
    ports:
      - 8191:8191
