version: "2"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - $PWD/lidarr/config:/config
      - $PWD/lidarr/music:/music
      - $PWD/qbittorrent/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - $PWD/sonarr/data:/config
      - $PWD/jellyfin/data/tvshows:/tvshows
      - $PWD/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      #- UMASK_SET=022 # control permissions of files and directories created by Radarr
      - TZ=Asia/Jakarta
      - PUID=1000
      - PGID=1000
    volumes:
      - $PWD/jellyfin/data/movies:/movies
      - $PWD/qbittorrent/downloads:/downloads
      - $PWD/radarr/config:/config
    ports:
      - 7878:7878

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - WEBUI_PORT=10010
    dns:
      - 1.1.1.1
    volumes:
      - $PWD/qbittorrent/config:/config
      - $PWD/qbittorrent/downloads:/downloads
      - $PWD/jellyfin/data/tvshows:/tvshows
      - $PWD/jellyfin/data/movies:/movies
    ports:
      - 10010:10010
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  whisparr:
    image: cr.hotio.dev/hotio/whisparr
    container_name: whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - $PWD/whisparr/config:/config
      - $PWD/qbittorrent/downloads:/downloads
    ports:
      - 6969:6969

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - $PWD/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta

    volumes:
      - $PWD/jellyfin/data/library:/config
      - $PWD/jellyfin/data/tvshows:/data/tvshows
      - $PWD/jellyfin/data/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
