version: "2"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /opt/stacks/sonarr/data:/config
      - /opt/stacks/jellyfin/data/tvshows:/tvshows
      - /opt/stacks/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      #- UMASK_SET=022 # control permissions of files and directories created by Radarr
      - TZ=Asia/Jakarta
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/stacks/jellyfin/data/movies:/movies
      - /opt/stacks/qbittorrent/downloads:/downloads
      - /opt/stacks/radarr/config:/config
    ports:
      - 7878:7878

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - WEBUI_PORT=10010
    dns:
      - 1.1.1.1
    volumes:
      - /opt/stacks/qbittorrent/config:/config
      - /opt/stacks/qbittorrent/downloads:/downloads
      - /opt/stacks/jellyfin/data/tvshows:/tvshows
      - /opt/stacks/jellyfin/data/movies:/movies
    ports:
      - 10010:10010
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /opt/stacks/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta

    volumes:
      - /opt/stacks/jellyfin/data/library:/config
      - /opt/stacks/jellyfin/data/tvshows:/data/tvshows
      - /opt/stacks/jellyfin/data/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
