services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    restart: always
    ports:
      - "8200:8200"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./config:/config
      - ./backups:/backups
      - ./sourcedata:/source
